/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ComboBoxYonetici;
import controller.HavaDurumuYonetici;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Transparency;
import java.awt.event.ItemEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;
import model.HavaDurumu;
import model.RotatedIcon;
import model.Sehir;

/**
 *
 * @author asimsinanyuksel
 */
public class HavaDurumuFrame extends javax.swing.JFrame {
    
    private HavaDurumuYonetici hdc;
    private ComboBoxYonetici cby;

    /**
     * Creates new form HavaDurumuFrame
     */
    public HavaDurumuFrame() {
        initComponents();
        hdc=new HavaDurumuYonetici();
        cby=new ComboBoxYonetici(sehirlerListe);
        try {
            cby.setSehirler(hdc.tumSehirleriGetir());
            cby.icerikOlustur();
        } catch (Exception ex) {
            Logger.getLogger(HavaDurumuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        havaDurumPanel = new javax.swing.JPanel();
        hadisePanel = new javax.swing.JPanel();
        hadiseKoduLabel = new javax.swing.JLabel();
        hadiseMetinLabel = new javax.swing.JLabel();
        basincPanel = new javax.swing.JPanel();
        basincLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nemPanel = new javax.swing.JPanel();
        nemLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ruzgarPanel = new javax.swing.JPanel();
        ruzgarYonuLabel = new javax.swing.JLabel();
        ruzgarHiziLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sicaklikPanel = new javax.swing.JPanel();
        sicaklikLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yagisPanel = new javax.swing.JPanel();
        yagisLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sehirlerListe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MGM Hava Durumu");

        havaDurumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hava Durumu Bilgileri", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        havaDurumPanel.setLayout(new java.awt.GridLayout(2, 0));

        hadisePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hava", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        hadiseKoduLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        hadiseKoduLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hadiseKoduLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hadiseMetinLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        hadiseMetinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout hadisePanelLayout = new javax.swing.GroupLayout(hadisePanel);
        hadisePanel.setLayout(hadisePanelLayout);
        hadisePanelLayout.setHorizontalGroup(
            hadisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hadisePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(hadiseKoduLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(hadiseMetinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hadisePanelLayout.setVerticalGroup(
            hadisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hadisePanelLayout.createSequentialGroup()
                .addComponent(hadiseKoduLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hadiseMetinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        havaDurumPanel.add(hadisePanel);

        basincPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basınç", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        basincLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        basincLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basincLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/basinc.png"))); // NOI18N

        javax.swing.GroupLayout basincPanelLayout = new javax.swing.GroupLayout(basincPanel);
        basincPanel.setLayout(basincPanelLayout);
        basincPanelLayout.setHorizontalGroup(
            basincPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basincPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel5)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(basincLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        basincPanelLayout.setVerticalGroup(
            basincPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basincPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(basincLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        havaDurumPanel.add(basincPanel);

        nemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        nemLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nemLabel.setToolTipText("");
        nemLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/nem.png"))); // NOI18N

        javax.swing.GroupLayout nemPanelLayout = new javax.swing.GroupLayout(nemPanel);
        nemPanel.setLayout(nemPanelLayout);
        nemPanelLayout.setHorizontalGroup(
            nemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nemPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        nemPanelLayout.setVerticalGroup(
            nemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nemPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        havaDurumPanel.add(nemPanel);

        ruzgarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rüzgar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        ruzgarYonuLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        ruzgarYonuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ruzgarYonuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/yon.png"))); // NOI18N
        ruzgarYonuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ruzgarHiziLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ruzgarHiziLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ruzgarHiziLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("Yön");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hız");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ruzgarPanelLayout = new javax.swing.GroupLayout(ruzgarPanel);
        ruzgarPanel.setLayout(ruzgarPanelLayout);
        ruzgarPanelLayout.setHorizontalGroup(
            ruzgarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ruzgarHiziLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(ruzgarPanelLayout.createSequentialGroup()
                .addGroup(ruzgarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ruzgarPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2))
                    .addGroup(ruzgarPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ruzgarPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(ruzgarYonuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ruzgarPanelLayout.setVerticalGroup(
            ruzgarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ruzgarPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ruzgarYonuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruzgarHiziLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        havaDurumPanel.add(ruzgarPanel);

        sicaklikPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sıcaklık", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        sicaklikLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sicaklikLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sicaklikLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/sicaklik.png"))); // NOI18N

        javax.swing.GroupLayout sicaklikPanelLayout = new javax.swing.GroupLayout(sicaklikPanel);
        sicaklikPanel.setLayout(sicaklikPanelLayout);
        sicaklikPanelLayout.setHorizontalGroup(
            sicaklikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sicaklikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sicaklikPanelLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
        );
        sicaklikPanelLayout.setVerticalGroup(
            sicaklikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sicaklikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(sicaklikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        havaDurumPanel.add(sicaklikPanel);

        yagisPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yağış", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        yagisLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        yagisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yagisLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/yagmur.png"))); // NOI18N

        javax.swing.GroupLayout yagisPanelLayout = new javax.swing.GroupLayout(yagisPanel);
        yagisPanel.setLayout(yagisPanelLayout);
        yagisPanelLayout.setHorizontalGroup(
            yagisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yagisPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel7)
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(yagisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        yagisPanelLayout.setVerticalGroup(
            yagisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yagisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(yagisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        havaDurumPanel.add(yagisPanel);

        sehirlerListe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sehirlerListeItemStateChanged(evt);
            }
        });
        sehirlerListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehirlerListeActionPerformed(evt);
            }
        });

        jLabel1.setText("Şehir Seç:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sehirlerListe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(514, 514, 514))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(havaDurumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sehirlerListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(havaDurumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public static BufferedImage createTransformedImage(BufferedImage image, double angle) {
        double sin = Math.abs(Math.sin(angle)), cos = Math.abs(Math.cos(angle));
        int w = image.getWidth(), h = image.getHeight();
        int neww = (int) Math.floor(w * cos + h * sin), newh = (int) Math.floor(h * cos + w * sin);
        BufferedImage result = new BufferedImage(neww, newh, Transparency.TRANSLUCENT);
        Graphics2D g2d = result.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.translate((neww - w) / 2, (newh - h) / 2);
        g2d.rotate(angle, w / 2, h / 2);
        g2d.drawRenderedImage(image, null);
        g2d.dispose();
        return result;
    }
    private void sehirlerListeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sehirlerListeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
             try {
            Sehir sehir=(Sehir)sehirlerListe.getSelectedItem();
            HavaDurumu hd= hdc.havaDurumuGetir(sehir.getMerkezId());
            sicaklikLabel.setText(hd.getSicaklik()+" °C");
            hadiseKoduLabel.setIcon(HavaDurumuYonetici.resimOlustur(hd.getHadiseKodu()));
            ruzgarYonuLabel.setIcon(HavaDurumuYonetici.resimOlustur("yon"));
            hadiseMetinLabel.setText(hdc.hadiseKodunuMetineDonustur(hd.getHadiseKodu()));
            yagisLabel.setText(hd.getYagis00Now()+" mm");
            RotatedIcon r1 = new RotatedIcon(ruzgarYonuLabel.getIcon(),Integer.valueOf(hd.getRuzgarYon()));
            ruzgarYonuLabel.setIcon(r1);
            nemLabel.setText("%"+hd.getNem());
            basincLabel.setText(Double.valueOf(hd.getDenizeIndirgenmisBasinc()).intValue()+" hPa");
            ruzgarHiziLabel.setText(Double.valueOf(hd.getRuzgarHiz()).intValue()+" km/sa");           
            TitledBorder br=(TitledBorder) havaDurumPanel.getBorder();
            br.setTitle(sehir.getIl()+" için Hava Durumu");
        } catch (Exception ex) {
            Logger.getLogger(HavaDurumuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          
       }
    }//GEN-LAST:event_sehirlerListeItemStateChanged

    private void sehirlerListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehirlerListeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehirlerListeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HavaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HavaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HavaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HavaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HavaDurumuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basincLabel;
    private javax.swing.JPanel basincPanel;
    private javax.swing.JLabel hadiseKoduLabel;
    private javax.swing.JLabel hadiseMetinLabel;
    private javax.swing.JPanel hadisePanel;
    private javax.swing.JPanel havaDurumPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nemLabel;
    private javax.swing.JPanel nemPanel;
    private javax.swing.JLabel ruzgarHiziLabel;
    private javax.swing.JPanel ruzgarPanel;
    private javax.swing.JLabel ruzgarYonuLabel;
    private javax.swing.JComboBox<String> sehirlerListe;
    private javax.swing.JLabel sicaklikLabel;
    private javax.swing.JPanel sicaklikPanel;
    private javax.swing.JLabel yagisLabel;
    private javax.swing.JPanel yagisPanel;
    // End of variables declaration//GEN-END:variables
}
